view = "image-classification"
functions = "./functions/"
metadata = "cifar_pred.csv"
models = ["cifar_net_2", "cifar_net_5", "cifar_net_10", "cifar_net_20"]
data_path = "./data/CIFAR-10-images/test/"
data_column = "id"
id_column = "id"
label_column = "label"
batch_size = 32
samples = 80
port = 8000
