view = "audio-transcription"
functions = "./functions/"
models = ["silero_sst", "whisper"]
metadata = "metadata.csv"
data_path = "/Users/acabrera/dev/data/speech-accent-archive/recordings/recordings/"
data_column = "id"
id_column = "id"
label_column = "label"
port = 8123
